### ISSUE TITLE
Check failed: currentSeqNum >= currBlock. end + 2 (1 vs. 2)

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#138]
Hi recently I bump into a problem using mvfst  to transfer some files

> [QuicWriteCodec.cpp:219] Check failed: currentSeqNum >= currBlock. end + 2 (1 vs. 2) ***Check failure stack trace: ***

I notice that structure of AckBlocks consists of IntervalSet, and this check failure occured because of the violation of its structure. I wonder what kind of reasons could results in this problem. Thanks!

**Comment by lnicco** [comment]
hi @Enjia thanks for reporting, it looks buggy. 
do you have any repro step that could help us get the same condition triggered ?
and do you have any modification to the mvfst code ?

**Comment by Enjia** [comment]
I wrote some demo code aiming to tranfer several files using multi connections. In detail, I use 5 connections to transfer a file, and based on this method, I try to transfer 5 files concurrently, and client show me this error probabilistically.
Yes I modified mvfst code:
1.QuicPacketSchedule.cpp line148 
ackScheduler_->writeNextAcks(builder, ackMode)——>ackScheduler_->writeNextAcks(wraper, ackMode)
2.QuicTransportFunctions.cpp line786
congestionControlWritableBytes——>unlimitedWritableBytes
3.QuicTransportFunctions.cpp line1209
remove code: increaseNextPacketNum(connection, pnSpace);

**Comment by lnicco** [comment]
thanks @Enjia may I ask what is the rationale behind those modifications ? 
if you believe that the changes you made would be good in general for mvfst you can open a pull request. 

in the mvfst codebase we use CHECK() as invariants, it means that the block of code below the invariant is only meaningful if the condition holds. If some changes make it so that the invariant is not valid anymore, it is likely that the block of code after the violated invariant needs to change as well. 

I am closing this issue, but as I said please feel free to post a Pull Request if you want us to merge some changes, otherwise, it is hard for us to support any 3-rd party modification to the core code.
