### ISSUE TITLE
GSO question

### ISSUE THREAD

**Issue by Ellie-fans** [facebookincubator/mvfst#146]
Hi~I comb the calling process of GSO in the code,  I found that 
constexpr uint64_t kDefaultV4UDPSendPacketLen = 1252;
parameter is transmitted to the AsyncUDPSocket::writev function and print gso parameter using LOG(INFO) found that upper bound is 1252, and IOBuf::length()  upper limit is also 1252 which cause  toplimit of one iovec struct size is also 1252, and iovec struct will finally pass into sendmsg function, does it means ip layer don't need to fragment packet any more? If it reallly dose, so the improvemance of turning on gso is just because of reducing traversal protocol stack which brings more operating system calls?
I would appreciate it if you replied this.

**Comment by mjoras** [comment]
The way GSO works for UDP is that the data that's submitted as part of the iovec is copied into a contiguous buffer in the kernel. This buffer is then sent through the network stack once. The actual packets, or "segments" are built just in time for sending on the wire.

This is compared with sendmmsg without GSO, where indeed one syscall is made, but the operation is different. Each buffer from the iovec is copied separately from userspace into new destinations, and each datagram traverses the network stack separately. It is literally a loop around a plain sendmsg.

The benefits of GSO are then primarily the eschewing of this looping. It is much faster for the kernel to segment a single buffer and do the associated routing lookups only once, rather than doing it for each individual packet.

**Comment by Ellie-fans** [comment]
Thank you very much
