### ISSUE TITLE
tests fail to build when libgmock is installed by an external package

### ISSUE THREAD

**Issue by yurivict** [facebookincubator/mvfst#170]
```
ninja: error: 'googletest/src/googletest-build/googlemock/libgmock.a', needed by 'quic/api/test/QuicTransportBaseTest', missing and no known rule to make it
*** Error code 1
```

The package ```googletest``` installed ```libgmock```:
```
$ pkg info -l googletest | grep libgmock
	/usr/local/lib/libgmock.so
	/usr/local/lib/libgmock_main.so
```

**Comment by xttjsn** [comment]
Is your building environment by any chance behind an http proxy? I've seen this one when the host doesn't have direct access to github. The cause seems to be that ExternalProject_Add doesn't pick up proxy settings, and thus cannot download googletest. Bu if your host have direct access to github, then that's an issue we should address.

**Comment by yurivict** [comment]
After the initial tarball is downloaded further internet access is prohibited during build for security reasons.

But this problems exists regardless of internet access.

**Comment by lnicco** [comment]
yeah this is a known issue, we are trying to get rid of ExternalProject.
hopefully soon

**Comment by lnicco** [comment]
removed ExternalProject. 
please update and try again. 
feel free to reopen this issue if experiencing similar problems
