### ISSUE TITLE
Some discussion about ACK feedback mechanism

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#193]
I noticed that the function updateAckSendStateOnRecvPacket within QuicStateFunctioins.cpp reset the value of numRxPacketsRecvd and numNonRxPacketsRecvd to zero apropos the response to sending ACK after the reception of retransmittable data. 

I have trouble in disentangling the logic why numRxPacketsRecvd and numNonRxPacketsRecvd is reset as soon as receiving packets because if there's a reset triggered by pktOutOfOrder then numRxPacketsRecvd and numNonRxPacketsRecvd will be zero, and needsToSendAckImmediately will be true, but when next packet in order comes, because of the reset, code will enters into "else" branch and set needsToSendAckImmediately to false. The ACKs should be sent are blocked due to it, which may leads to the accumulation of ACKs.

Furthermore, I added LOG(INFO) and founded the irregularity of ACK sent back to the sender. Some times receiver sent one ACK packet in response to 10 received packets or sometimes larger than 10, which occured incessantly. In my opinion I think it's better to have an even ACK feedback

Thereby I alter some logic within updateAckSendStateOnRecvPacket：

1. comment out all reset code about numRxPacketsRecvd and numNonRxPacketsRecvd
2. switch the code "++ackState.numRxPacketsRecvd + ackState.numNonRxPacketsRecvd >= thresh" from end to start to avoid the impact of pktOutOfOrder, that is:
`if (pktHasCryptoData || pktOutOfOrder || ++ackState.numRxPacketsRecvd + ackState.numNonRxPacketsRecvd >= thresh)`
now becomes
`if (++ackState.numRxPacketsRecvd + ackState.numNonRxPacketsRecvd >= thresh || pktHasCryptoData || pktOutOfOrder )`
3. change the rxPacketsBeforeAckAfterInit value from 10 to 30 to avoid frequent ACK feedback

After tests it comes out that with such modification the speed of tperf is higher than original one as well as more flat ACK feedback rather than some burst.

Now do you have any advice of my thoughts and if there's something I misunderstand? Thanks

**Comment by yangchi** [comment]
One packet sets the needsToSendAckImmediately flag to true, then next packet sets it back to false is an interesting observation. I think before we introduced batch read on the receiving side, this is fine, since after each packet receive & process, we update the write looper. But indeed with batch read, this might be problematic.

Regarding sometimes the code waits 10 packets and some times it waits more, this depends on if the received packets are ack eliciting.

I don't think there will be one value that's good for every appliation and every network. User has the freedom to change it's own ack behavir by changing rxPacketsBeforeAckBeforeInit/rxPacketsBeforeAckAfterInit/rxPacketsBeforeAckInitThreshold. What one doesn't have control is peer's acking behavior. There is a draft to add a new frame to make that controllable as well. We may look into implementing that next year.
