### ISSUE TITLE
Question about Connection ID in mvfst's implementation of QUIC

### ISSUE THREAD

**Issue by wtao0221** [facebookincubator/mvfst#269]
Hi team,

Suppose one host may have multiple QUIC connections. Will there any source or destination connection IDs be the same?

**Comment by mjoras** [comment]
They shouldn't be, otherwise there'd be no way to reliably distinguish the connections. CID generation thus has to have a degree of randomness in it to avoid such eventualities. You can see how our CID generation tries to account for this here: https://github.com/facebookincubator/mvfst/blob/main/quic/codec/DefaultConnectionIdAlgo.h#L18
