### ISSUE TITLE
The calculation of the sendRate in bbr's bandwidthsampler

### ISSUE THREAD

**Issue by yhcchaos** [facebookincubator/mvfst#292]
I have some confusion about the sendRate calculation when sampling the bandwith in quic/congestion_control/BbrBandwidthSampler.cpp.

the calculation is shown below：
       _**sendRate = Bandwidth(
          ackedPacket.outstandingPacketMetadata.totalBytesSent - ackedPacket.lastAckedPacketInfo->totalBytesSent,
          std::chrono::duration_cast<std::chrono::microseconds>(
ackedPacket.outstandingPacketMetadata.time -ackedPacket.lastAckedPacketInfo->sentTime)
);**_

we assume the acked packet is m, the last acked packet before m is n.
ackedPacket.outstandingPacketMetadata.totalBytesSent is the total sent bytes when m is sent.
ackedPacket.lastAckedPacketInfo->totalBytesSent is the total sent bytes  when n is acked.
ackedPacket.outstandingPacketMetadata.time  is m's sent time.
ackedPacket.lastAckedPacketInfo->sentTime is the sent time of  n.
When n is acked, there are still lots of inflight bytes which are sent after the sent time of n.
And ackedPacket.outstandingPacketMetadata.totalBytesSent -ackedPacket.lastAckedPacketInfo->totalBytesSent doesn't contain these infight bytes.
But ackedPacket.outstandingPacketMetadata.totalBytesSent - ackedPacket.lastAckedPacketInfo->totalBytesSent is the duration between the sent time of n and m, which contain the inflight bytes.
So I think the calculation of the sendRate is wrong.
Could you please answer my doubts? thanks very much.

**Comment by jbeshay** [comment]
> But ackedPacket.outstandingPacketMetadata.totalBytesSent - ackedPacket.lastAckedPacketInfo->totalBytesSent is the duration between the sent time of n and m, which contain the inflight bytes.

I assume you meant `ackedPacket.outstandingPacketMetadata.time -ackedPacket.lastAckedPacketInfo->sentTime`

I *think* the confusion comes from the definition of n and totalBytesSent. 
- If the acked packet is m, then n is the last acked packet *when m was sent*.
- totalBytesSent is the total number of bytes sent by the connection *when the packet was sent*.

The goal of the calculation is to find the a *sending rate* sample from the info in m.

Time spent= m.send_time - n.send_time
Bytes sent=m.total_bytes_sent - n.total_bytes_sent

Note that total_bytes_sent is the total number of bytes sent by the connection when the packet was sent. By definition, n is the last packet *acked* when m was sent, so m.total_bytes_sent *includes* inflight bytes. Basically, (m.total_bytes_sent - n.total_bytes_sent) is all the inflight bytes that were sent between n and m. And that's correct because we are calculating the *sending rate*.

I hope this helps. Please let me know if I didn't understand your concern correctly.
