### ISSUE TITLE
Do you have android client support mvfst server?

### ISSUE THREAD

**Issue by ChuLiqiang** [facebookincubator/mvfst#31]
I want develop an android app use QUIC,Can you tell me which android client can use and compatibility this mvfst server?thank you very much.

**Comment by yangchi** [comment]
Our client works on Android. But you will need to figure out how to integrate mvfst into your use case. For example, the TCP vs Quic racing isn't in mvfst but you need to have it in your integration layer There is also no JNI for mvfst at the moment. If your integration layer already has JNI, great. Otherwise, you will need to build that as well if you will send requests from Java.

Regarding other IETF Quic implementations, I think we interop with probably all of them. But i'm not aware if they support android as a client. A few of them are in C or C++ so you can potentially build with Android NDK as well. But then same thing as I said above: you need a integration/JNI layer on top of them.

I think all these are are beyond the support we will provide on this github repo, at least for now. If you run into build errors during the integration or after integrate mvfst into Android you run into other problems, then of course feel free to open more issues.

**Comment by lnicco** [comment]
alternatively, you would need a QUIC Java implementation that you can use directly in Android. 
At this time and to the best of our knowledge there is no such library available.
