### ISSUE TITLE
Pakets get dropped because tperf client sends too large pakets

### ISSUE THREAD

**Issue by valkum** [facebookincubator/mvfst#89]
Using the default values for max_receive_packet_size all pakets from the tperf client get dropped because they are truncated on Linux and macOS using the loopback device.

Tested this inside a docker container, a Linux VM and native macOS.

The default for IPv6 is 1233 bytes but somehow the client sends initial pakets larger than that.
If I manually set max_receive_packet_size to 1235 bytes it works.

I collected a pcap trace of the packets from the client and can upload that in a couple of days if needed.

**Comment by yangchi** [comment]
I think this is due to a recent change to just set canIgnorePathMTU to true: https://github.com/facebookincubator/mvfst/commit/c41ae9203403f84a2bc1dfde81a9a9ca67b77281#diff-5486f01bb4ef1401a81a1d213e38f5e8

You can set a smaller max_receive_packet_size via cmdline option when you run tperf to get around that.

**Comment by yangchi** [comment]
> The default for IPv6 is 1233 bytes but somehow the client sends initial pakets larger than that.
If I manually set max_receive_packet_size to 1235 bytes it works.

Yes we also recently noticed we miscount by 3. :( This will be fixed.

**Comment by yangchi** [comment]
Oh wait, in your case it's off by 2.

**Comment by valkum** [comment]
The difference is `kDefaultUDPReadBufferSize `vs `kDefaultUDPSendPacketLen`

**Comment by yangchi** [comment]
kDefaultUDPSendPacketLen should be 1232.
Then the miscounting bug will lead to building out 1235 bytes packets.
So you are saying 1235 won't traverse your network?
By the way the miscounting will be fixed today.

**Comment by valkum** [comment]
According to my trace the packets the client sends are 1297 bytes (1243 bytes udp payload only, 1235 bytes quic payload only) long.
Prior to that change the read buffer in the server was bigger so the packets weren't dropped.
With the current default values, the client packets are too large and get dropped here: https://github.com/facebook/folly/blob/d4d80f774a5de7364884e764507143be95b46ed0/folly/io/async/AsyncUDPSocket.cpp#L635 
Thus the server does not receive any packets.

**Comment by yangchi** [comment]
Ah, i see. Ye that makes sense. I think we saw this on our test as well. It has nothing to do with traversing the network. It's a drop at the receiver due to the buffer size and the sent packet 3 bytes larger than that.

Defaulting max_receive_packet_size  to kDefaultUDPSendPacketLen is also a mistake. The sender actually doesn't send using kDefaultUDPSendPacketLen as size limit even if we fix the miscounting bug. Client will use with the v4 length or v6 length after it learns the server address family. This needs to be fixed too.

**Comment by yangchi** [comment]
Fix of the miscounting: https://github.com/facebookincubator/mvfst/commit/cdf60f3eb187e80f94a4486733f0097130587fb5

**Comment by yangchi** [comment]
hey can you pull latest and try again? The default receive packet size should also be fixed now.

**Comment by valkum** [comment]
Current master seems to work. I consider this fixed.
